#!/usr/bin/env ruby

require 'jenkins_api_client'

@client = JenkinsApi::Client.new(
  :server_url => 'https://jhoblitt-test-ci.lsst.codes',
  :username   => 'jhoblitt',
  :password   => ARGV[0],
  :log_level  => Logger::DEBUG,
)

def groovy
  script = File.read(ARGV[1])
  text = @client.exec_script(script)
  puts text
end

groovy
