import util.Plumber

def p = new Plumber(name: 'release/codekit/github-tag-release', dsl: this)
p.pipeline().with {
  parameters {
    stringParam('GIT_TAG', null, 'git tag string. Eg. w.2018.22')
    stringParam('EUPS_TAG', null, 'eups tag string. Eg. w_2018_22')
    stringParam('BUILD_ID', null, 'BUILD_ID generated by lsst_build to generate EUPS distrib packages from. Eg. b3638')
    booleanParam('DRY_RUN', true, 'Dry run')
    stringParam('LIMIT', '3', 'limit operation to N products (only for testing)')
  }
}
