import util.Plumber

def p = new Plumber(name: 'release/codekit/github-tag-version', dsl: this)
p.pipeline().with {
  parameters {
    stringParam('BUILD_ID', null, 'BUILD_ID generated by lsst_build to generate EUPS distrib packages from. Eg. b1935')
    stringParam('GIT_TAG', null, 'git tag string. Eg. w.2016.08')
    booleanParam('DRY_RUN', true, 'Dry run')
  }
}
