import util.Plumber

def p = new Plumber(name: 'release/codekit/github-tag-release', dsl: this)
p.pipeline().with {
  def text = '''
    Tag git repositories, in a GitHub org, that correspond to the products in
    a published eups distrib tag.

    Example:

      $ github-tag-release \
        --dry-run \
        --verify \
        --debug \
        --org 'lsst' \
        --allow-team 'Data Management' \
        --allow-team 'DM Externals' \
        --external-team 'DM Externals' \
        --deny-team 'DM Auxilliaries' \
        --email 'sqre-admin@lists.lsst.org' \
        --user 'sqreadmin' \
        --token "$GITHUB_TOKEN" \
        --limit 10 \
        --manifest 'b7777' \
        'w.9999.52'
  '''
  description(text.replaceFirst("\n","").stripIndent())

  parameters {
    stringParam('GIT_TAG', null, 'git tag string. Eg. w.9999.52')
    stringParam('EUPS_TAG', null, 'eups tag string. Eg. w_9999_52')
    stringParam('MANIFEST_ID', null, 'MANIFEST_ID generated by lsst_build to generate EUPS distrib packages from. Eg. b7777')
    booleanParam('DRY_RUN', true, 'Dry run')
    stringParam('LIMIT', '3', 'limit operation to N products (only for testing)')
    booleanParam('VERIFY', false, 'Verify a previous release -- will not create git tags')
    booleanParam('MANIFEST_ONLY', false, 'Do not cross reference a published eups tag with the manifest -- use only the metadata from the manifest to determine git tag location. This allows a git tag to be created without a prior eups tag.')
  }
}
