job('release/tag-git-repos') {

  parameters {
    stringParam('BUILD_ID', null, 'BUILD_ID generated by lsst_build to generate EUPS distrib packages from. Eg. b1935')
    stringParam('TAG', null, 'EUPS distrib tag name to publish. Eg. w_2016_08')
    booleanParam('DRY_RUN', 'Dry run')
  }

  scm {
    git {
      remote {
        github('lsst-sqre/sqre-codekit')
        //refspec('+refs/pull/*:refs/remotes/origin/pr/*')
      }
      branch('*/master')
      extensions {
        cloneOptions {
          shallow(true)
        }
      }
    }
  }

  properties {
    rebuild {
      autoRebuild()
    }
  }

  // python 2.7 is required
  label('centos-7')
  concurrentBuild(false)

  wrappers {
    credentialsBinding {
      string('GITHUB_TOKEN', 'github-api-token-jhoblitt')
    }
  }

  steps {
    shell(
      '''
      virtualenv venv
      . venv/bin/activate
      pip install -r requirements.txt
      python setup.py install
      set +x
      # do not echo GH token to console log
      github-tag-version --org lsst --team 'Data Management' --dry-run --token $GITHUB_TOKEN $TAG $BUILD_ID --email sqre-admin@lists.lsst.org --tagger sqreadmin --debug
      '''.stripIndent()
    )
  }

  publishers {
    // must be defined even to use the global defaults
    hipChat {}
  }
}
