import util.Plumber
import org.yaml.snakeyaml.Yaml

def scipipe = new Yaml().load(readFileFromWorkspace('etc/scipipe/build_matrix_test.yaml'))

def p = new Plumber(name: 'release/docker/test-build-stack', dsl: this)
p.pipeline().with {
  description('Constructs docker images with EUPS tarballs. (TEST)')

  parameters {
    stringParam('PRODUCTS', scipipe.canonical.products,
      'Whitespace delimited list of EUPS products to build.')
    stringParam('EUPS_TAG', null, 'EUPS distrib tag name. Eg. w_9999_52')
    booleanParam('NO_PUSH', false, 'Do not push image to docker registry.')
    stringParam('TIMEOUT', '2', 'build timeout in hours')
    stringParam('DOCKER_TAGS', null, '(Optional) whitespace delimited list of additional docker image tags.')
    stringParam('MANIFEST_ID', null, '(Optional) MANIFEST_ID/BUILD_ID/BUILD/bNNNN generated by lsst_build.')
    stringParam('LSST_COMPILER', null, '(Optional) LSST_COMPILER string. Eg. devtoolset-6')
  }

  concurrentBuild(true)
}
