import util.Plumber

def p = new Plumber(name: 'sqre/validate_drp', dsl: this)
p.pipeline().with {
  description('Execute validate_drp and ship the results to the squash qa-dashboard.')

  parameters {
    stringParam('EUPS_TAG', 'w_2017_45', 'EUPS distrib tag name. Eg. w_2016_08')
    stringParam('BNNNN', 'b3211', 'BNNNN generated by lsst_build to generate EUPS distrib packages from. Eg. b1935')
    booleanParam('NO_PUSH', true, 'Do not push results to squash.')
    booleanParam('WIPEOUT', false, 'Completely wipe out workspace(s) before starting build.')
  }
}
