import util.Plumber

def p = new Plumber(name: 'sqre/validate_drp', dsl: this)
p.pipeline().with {
  description('Execute validate_drp and ship the results to the squash qa-dashboard.')

  parameters {
    stringParam('EUPS_TAG', null, 'EUPS distrib tag name. Eg. w_2017_45')
    stringParam('MANIFEST_ID', null, 'MANIFEST_ID/BUILD_ID/BUILD/bNNNN generated by lsst_build to generate EUPS distrib packages from. Eg. b3211')
    stringParam('COMPILER', null, 'compiler version string')
    stringParam('RELEASE_IMAGE', null, '(optional) Explicit name of release docker image including tag.')
    booleanParam('NO_PUSH', true, 'Do not push results to squash.')
    booleanParam('WIPEOUT', false, 'Completely wipe out workspace(s) before starting build.')
  }
}
