import util.Common
Common.makeFolders(this)

def folder = 'sqre'

pipelineJob("${folder}/validate_drp") {
  description('Execute validate_drp and ship the results to the squash qa-dashboard.')

  parameters {
    stringParam('EUPS_TAG', 'w_2017_45', 'EUPS distrib tag name. Eg. w_2016_08')
    stringParam('BUILD_ID', 'b3211', 'BUILD_ID generated by lsst_build to generate EUPS distrib packages from. Eg. b1935')
    booleanParam('NO_PUSH', true, 'Do not push results to squash.')
    booleanParam('WIPEOUT', false, 'Completely wipe out workspace(s) before starting build.')
  }

  properties {
    rebuild {
      autoRebuild()
    }
  }

  // don't tie up a beefy build slave
  label('jenkins-master')
  concurrentBuild(false)
  keepDependencies(true)

  def repo = SEED_JOB.scm.userRemoteConfigs.get(0).getUrl()
  def ref  = SEED_JOB.scm.getBranches().get(0).getName()

  definition {
    cpsScm {
      scm {
        git {
          remote {
            url(repo)
          }
          branch(ref)
        }
      }
      scriptPath("pipelines/${folder}/validate_drp.groovy")
    }
  }
}
