apiVersion: v1
kind: Service
metadata:
  name: {{ include "lsst-jenkins-swarm-agent.fullname" . }}
  labels:
    {{- include "lsst-jenkins-swarm-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lsst-jenkins-swarm-agent.selectorLabels" . | nindent 4 }}
  # See https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
  clusterIP: None
