extends: default
rules:
  document-start: {present: false}
  line-length:
    max: 800
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  indentation:
    indent-sequences: consistent
